### ISSUE TITLE
Exact versions of libraries

### ISSUE THREAD

**Issue by ogencoglu** [explodinggradients/ragas#106]
HuggingFace is famous for moving fast and breaking things. Would be great to have the exact dependency versions of all the python libraries. Something like "`datasets==2.14.3`" instead of `datasets`.

**Comment by shahules786** [comment]
Hi @ogencoglu, thanks for raising this issue. 
@jjmachan

**Comment by jjmachan** [comment]
thanks again for raising the issue and help make ragas more robust, I really appreciate it Oguzhan :)
while I do agree that it is a chance for error, I don't think pinning a version is a solution in the long term. We will miss out on important bug fixes and security updates that might be release later. But I do think ragas has to do a better job at testing the dependencies so that if and when they change stuff, we make the required changes as well and don't break things. 

as for tiktoken, I don't think we use that internally in ragas and hence not a dependency, do correct me if I'm wrong @shahules786 @ogencoglu. could you share a bit more about the error you're facing so I know where its coming from.

do let me know your thoughts Oguzhan, much appreciated

**Comment by ogencoglu** [comment]
I'll close this for now. My hypothesis is that you will have more work dealing with users issues due to not fixing the versions than the work to test the latest versions.
