### ISSUE TITLE
Can we turn off eval verbosity

### ISSUE THREAD

**Issue by ogencoglu** [explodinggradients/ragas#108]
Can we prevent printing the progress and other logs?

**Comment by jjmachan** [comment]
now right now but I will make a fix for this by next week.

but could you tell me a bit more about what logs that you wanted to avoid? would it show no logs and only the results?

**Comment by ogencoglu** [comment]
A `verbose` or `verbosity` option to turn on/off all printing would be great

**Comment by yujonglee** [comment]
@ogencoglu  As a workaround, you can do something like this:
https://github.com/repllabs/fastrepl/blob/cf4e4f6ee743691d1df2d5dadf0f61add3ee95b0/fastrepl/eval/model/ragas.py#L194

**Comment by atursunov** [comment]
I am integrating ragas into different platform and below messages are annoying. Can we turn it off in settings please?

![image](https://github.com/explodinggradients/ragas/assets/7220691/ebe425d6-5ea7-452f-aa1d-a6684bd805b1)

**Comment by jjmachan** [comment]
hey @atursunov - could you explain a bit more about why you want *every* logs removed so that I can understand your usecase a bit better? 
without progress bars it will be hard to know the progress for `evaluations()`

**Comment by jjmachan** [comment]
I see that you feel very strongly about this :)
have you had a chance to take a look at the latest? We have reduced the logs to just a progress bar as shown.
![image](https://github.com/explodinggradients/ragas/assets/5261489/320d72a8-e13a-4cf8-8327-0ea5187ffc26)
do you want to disable that too?

the reason is that I'm also thinking about how to show debug logs. the 2 options we have are `logging` module in python, which is not so great for LLM outputs and such and the `callbacks` in langchain_core which are very good at tracing. docs here [Logging and tracing | Ragas](https://docs.ragas.io/en/latest/howtos/applications/tracing.html)

would love to here you thoughts on this

**Comment by alexjyong** [comment]
@jjmachan  I'll open up another issue for this, but I was curious if there was an option to do the exact opposite, more verbose logs. I would be curious to understand ragas is arriving at the scores it does. 

Currently for example, on faithfulness, I can add a print statement here to see the rough json output of the scores:
https://github.com/explodinggradients/ragas/blob/main/src/ragas/metrics/_faithfulness.py#L201

But it would be nice if I could turn that on with a config flag or something. Does this already exist?

**Comment by jjmachan** [comment]
hey @alexjyong where were you able to figure it out?
the recommended way is to use some traces

closing this for now, feel free to reopen if needed

**Comment by alexjyong** [comment]
@jjmachan  I'm sorry I have been working on other projects at work so I haven't had much time to play with ragas. I'll check out the latest features and see if that fits our needs. thank you!
