### ISSUE TITLE
[R-279] [R-280] Summarization Score Formula is unreasonable

### ISSUE THREAD

**Issue by ofooo** [explodinggradients/ragas#1108]
I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
I read the doc for summarization Score.
https://docs.ragas.io/en/stable/concepts/metrics/summarization_score.html

![1](https://github.com/user-attachments/assets/980558eb-be3e-4870-af75-f8a23ac34bca)

QA score, **higher is better**. range is (0, 1).

but, consiseness score, **lower is better**. range is (0, infinity).

so, summarization score = (QA score + conciseness score)/2, It's unreasonable.

I  think the "consiseness score" should be converted into a valut that range is (0, 1), and the larger the better.

Ragas version: stable

<sub>[R-280](https://linear.app/exploding-gradients/issue/R-280/summarization-score-formula-is-unreasonable)</sub>

**Comment by shahules786** [comment]
Hey @ofooo good point. I will take care of it this week.

**Comment by sky-2002** [comment]
Hey @ofooo , you are absoultely correct, In the code, its correct, I missed this in docs, I have updated the docs
But yes, we need to handle cases where summary length is higher than text length, we can straightaway assign 0 score maybe
![image](https://github.com/user-attachments/assets/38283044-980b-41a0-98fe-35fd3e97075f)

**Comment by shahules786** [comment]
Thanks for pitching in @sky-2002 and pointing out the issue @ofooo 
@sky-2002 can you fix that edge case in the summarisation metric?
Another point I would like to make is summaries can be hard to score in general - even humans struggle with it. In coming versions, we will add support to ranking based metrics (it's easier to rank such tasks)

**Comment by sky-2002** [comment]
@shahules786 interesting points you made, we can discuss these in the above PR I created or on discord, there are more points to discuss on summarization, 
@ofooo you can also join the discussion in the PR, suggestions are welcome

**Comment by shahules786** [comment]
Hey @ofooo @sky-2002 An easy and intuitive fix for this is modify conciseness score as

`conciseness score = length of summary / (length of context + 1) `
thereby mapping into range of (0,1)

Then since a conciseness score, lower is better , we take (1 - consiseness score) when combining it with the QA score

So final will be = `[QA Score + (1 - consiseness_score) ] / 2`

One more suggestion, here we have assumed both to be QA and consiness to be equal weightage, but ideally user should be able to control it. So adding an extra argument as `coeff` (which is 0-1) , the score would be

`score =  coeff * QA Score + (1-coeff) *(1 - consiseness_score)`

How does that look guys?

**Comment by sky-2002** [comment]
Great idea @shahules786 , I had proposed this weighing initially but we didnt want too much work on the user side, but anyways, its good to let user control it, fixing it right away
