### ISSUE TITLE
My faithfulness and context_recall is incorrect。

### ISSUE THREAD

**Issue by PurpleLikeNero** [explodinggradients/ragas#148]
I set OPENAI_API_BASE to my own deployed model, and then there were some errors in the data evaluated by Ragas.
First, the same data produces different results each time it's evaluated. Second, there are values outside the range, like -1, in faithfulnessn.
Is there something wrong with my model?how can i locate the bug
![5Y{E2@R{L K{AFO65W21E1Q](https://github.com/explodinggradients/ragas/assets/129468785/8dad95c1-9227-4033-beaa-b279a8aa1c13)

**Comment by shahules786** [comment]
Hi @PurpleLikeNero , the quality of results is highly dependent on the quality of the model. The default prompts in Ragas are tuned for OpenAI, you might want to tune it for your model. Are you using any opensource model?

**Comment by PurpleLikeNero** [comment]
> Hi @PurpleLikeNero , the quality of results is highly(高度) dependent(依赖) on the quality of the model. The default prompts in Ragas are tuned for OpenAI, you might want to tune it for your model. Are you using any opensource model?

yes, my using opensource model named [Qwen-7B](https://github.com/QwenLM/Qwen-7B)

**Comment by shahules786** [comment]
It's an interesting model. Do you use [Langsmith](https://github.com/explodinggradients/ragas/blob/main/docs/integrations/langsmith.ipynb) along with ragas? In that case, it would be easier to debug and change the prompt appropriately for your model.

**Comment by PurpleLikeNero** [comment]
> It's an interesting model. Do you use [Langsmith](https://github.com/explodinggradients/ragas/blob/main/docs/integrations/langsmith.ipynb) along with ragas? In that case, it would be easier to debug and change the prompt appropriately(适当) for your model.

ok,i will try this later.

**Comment by Robs1999** [comment]
@PurpleLikeNero did you manage to get better results? I am facing the same issue using as model Llama-2-13B-chat-GGUF (q6) and I think the problem could be with the prompts

**Comment by AbsoluteGravity** [comment]
I had an error in ContextRecall in _score_batch where the model (non-gpt) response didn't conform to the downstream processing requirements (Attributed vs [Attributed]). I would like to use a Pydantic output parser so that the responses can be better guided. i want to put it in _score_batch immediately after responses are collected or deeper in the LangchainLLM generate code which generates those responses. Any ideas or hints? Thanks

**Comment by jjmachan** [comment]
@AbsoluteGravity we actually made some improvements to reproducibility by using forcing the evaluator LLM to output it in json. @tinomaxthayil is the one working on this. @tinomaxthayil we could also look into Pydantic Output Parser and see how it compares to json output parser. 

i think json would be better though because the model will have been trained on json outputs and error messages (more likely than pydantic). would that be the case @shahules786 ?
