### ISSUE TITLE
context_relevancy not available?

### ISSUE THREAD

**Issue by chukwuderaMoj** [explodinggradients/ragas#228]
Has context_relevancy been depricated? I am unable to import it

**Comment by shahules786** [comment]
Hi @chukwuderaMoj , thanks for raising the issue. This will be fixed by #229 , please update ragas from the source once it is merged. We would also recommend you to try out `context_precision`, it is same as average precision mentioned [here](https://amitness.com/2020/08/information-retrieval-evaluation/#2-average-precisionap
)
