### ISSUE TITLE
Making custom LLMs compatible with TestsetGenerator?

### ISSUE THREAD

**Issue by Data-drone** [explodinggradients/ragas#230]
Hi Team,

I am trying to get the `TestsetGenerator` to work properly with a Langchain custom LLM.

It's `_call` method current expects a string prompt but it gets a `ChatPromptTemplate` from ragas. what is the best way to handle this?

**Comment by Data-drone** [comment]
I got things working by just running `format()` against the prompt my LLM received if it was in `ChatPromptTemplate` format but not sure that is the best approach.

I have set the `chat_qa=0.0` so shouldn't all the prompts be coming in as string?

**Comment by shahules786** [comment]
Hey @Data-drone , can you share the ragas & python version you're using?

**Comment by Data-drone** [comment]
ragas==0.0.18 python 3.10.12

**Comment by shahules786** [comment]
Hi @Data-drone , We will look into the langchain [custom](https://python.langchain.com/docs/modules/model_io/models/llms/custom_llm) llms issue. Regarding setting `chat_qa=0`, it is used to control if the test set should contain conversational questions or not.

**Comment by shahules786** [comment]
Hi @Data-drone , which model are you using? Are you using an instruction-tuned model (that is not chat based)?

**Comment by Data-drone** [comment]
Vicuna 1.5 13b

**Comment by jjmachan** [comment]
hey @Data-drone , so we do have this snipped inside RagasLLMs that should handle this logic for you
```py
        if isinstance(self.llm, BaseLLM):
            ps = [p.format() for p in prompts]
            result = self.llm.generate(ps, callbacks=callbacks)
        else:  # if BaseChatModel
            ps = [p.format_messages() for p in prompts]
            result = self.llm.generate(ps, callbacks=callbacks)
```

if your custom model is a base class of either, it should do the conversation for you. but not sure why its not working here. Could you show us how you're calling the testsetgenerator and custom models code?

**Comment by msunkarahend** [comment]
@shahules786 @jjmachan In the same context, TestsetGenerator uses cross-encoder/stsb-TinyBERT-L-4/ from hugging face. Is there a way,  i can avoid using that and just use gpt models from azure open ai alone and generate synthetic dataset?

**Comment by jjmachan** [comment]
but @shahules786 probably we should change `from_defaults` class method to `with_openai` or something like that to make it easier?

**Comment by msunkarahend** [comment]
@jjmachan If you can share the finished snippet for the TestsetGenerator, it would be great. thanks in advance.

**Comment by hbj52** [comment]
@jjmachan Hi, really nice program.  I just start using your program today, and after experiencing several hours, I have met something wired.

Is the github code same as code on pip? Because what I found out is like in the picture,  and the github shows that the latest version is v0.0.22. But the codes are different, at least for ragas.llm.base.BaseRagasLLM part. This is the first time I meet such problem, please forgive me if I misunderstand something.

![subscreen_0120](https://github.com/explodinggradients/ragas/assets/48450723/ad4915dc-7b35-4973-9cdf-235db970299c)

![subscreen_0120_2](https://github.com/explodinggradients/ragas/assets/48450723/9748a5d6-654f-41c2-a563-d90cf53ad7c5)


Background: I am trying to use llama2 with ragas, and when following the process of https://docs.ragas.io/en/stable/concepts/testset_generation.html
 to 
```
test_generator = TestsetGenerator(
    generator_llm=generator_llm,
    critic_llm=critic_llm,
    embeddings_model=embeddings_model,
    testset_distribution=testset_distribution,
    chat_qa=chat_qa,
)

testset = test_generator.generate(documents, test_size=5)
```




it returns errors about `list(str)` and `list(ChatPromptTemplate)`. And after searching codes in python and github, I found out this situation,  and it seems like here is on discussion about such problem.

**Comment by mspronesti** [comment]
Can you guys try #670?
