### ISSUE TITLE
TestsetGenerator with own LLM

### ISSUE THREAD

**Issue by weissenbacherpwc** [explodinggradients/ragas#342]
Hi,

I want to use the Ragas TestsetGenerator to create a synthetic dataset. The function is using OpenAI in the background, but I was wondering if you can set your own LLM to create the synthetic dataset? 

For example for evaluation it is possible to set an own LLM and not an OpenAI Model. Like here:
```
from ragas.llms import LangchainLLM
from src.llm import build_llm


llm = build_llm() # this is loading the Llama 2 model with LlamaCpp from Langchain
llm = LangchainLLM(llm=llm)
from ragas.metrics import (
    context_precision,
    answer_relevancy,
    faithfulness,
    context_recall,
)
from ragas.metrics.critique import harmfulness

# change the LLM

faithfulness.llm = llm
answer_relevancy.llm = llm
context_precision.llm = llm
context_recall.llm = llm
harmfulness.llm = llm
```

**Comment by jjmachan** [comment]
hey @weissenbacherpwc welcome to the community :)

this is possible you can create a new testset generation object to achieve it but the issue is that it might change in the future because testset generation is a beta feature.

but check the code [here](https://github.com/explodinggradients/ragas/blob/fe343d6fdcd0e11096fc1b8fbf4f36d289f32eaa/src/ragas/testset/testset_generator.py#L87) . you can create a new `TestsetGenerator` with any `LangchainLLM`
