### ISSUE TITLE
AzureOpenAIEmbeddings no longer exists on langchain

### ISSUE THREAD

**Issue by JeremyBon** [explodinggradients/ragas#361]
**Describe the bug**
Bug in import, cannot import AzureOpenAIEmbeddings because it no longer exists
Ragas version: 0.0.21

Langchain version: 0.0.325

**Code to Reproduce**
from ragas.metrics import (
    answer_relevancy,
    faithfulness,
    context_recall,
    context_precision,
)
from ragas import evaluate

**Error trace**
ImportError: cannot import name 'AzureOpenAIEmbeddings' from 'langchain.embeddings'
**Expected behavior**
Import works fine

**Comment by marceljahnke** [comment]
Try updating your langchain version to the latest version via: 

```python
pip install --upgrade langchain
```

AzureOpenAIEmbeddings were added in langchain release: https://github.com/langchain-ai/langchain/releases/tag/v0.0.331rc3
Your installed version of langchain is older, hence does not include the `langchain.embeddings.azure_openai.AzureOpenAIEmbeddings` class.


Be aware, **updating your version of langchain might require some adjustments in your code** regarding the openai evironment variables (`AZURE_OPEN_...` instead of `OPENAI_...`) and `AzureOpenaiAIChat` / `AzureOpenaiAIEmbeddings` class usage (`azure_endpoint` instead fo `openai_api_base`).
