### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by nils-hde** [explodinggradients/ragas#425]
**Describe the bug**
The latest commit has deleted a bunch of components and code references, this does not seem intentional / is not documented anywhere.

Ragas version: commit/bad3a8e1d115e69bb4acbd9887ca5b6cb6a03fba
Python version: 3.10

e.g. `langchain/` package is entirely missing

**Comment by nils-hde** [comment]
@jjmachan

**Comment by jjmachan** [comment]
hey welcome to the community :)
really sorry about that but we are removing these extra modules in preparation for our v0.1 release which is a major revamp. While the happy case has been kept migration free since a lot of internals have changed which will need to be migrated. 

I would love to help you migrate (by debugging on call) this since you are on the dev branch and hopefully it will get you unblocked and will help we write the migration docs for others as well - what do you think

**Comment by nils-hde** [comment]
@jjmachan hey sure that’s okay. For starters, how is the EvaluatorChain migrated (from the missing langchain package)?

```
from ragas.langchain.evalchain import RagasEvaluatorChain
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)

# create evaluation chains
faithfulness_chain = RagasEvaluatorChain(metric=faithfulness)
answer_rel_chain = RagasEvaluatorChain(metric=answer_relevancy)
context_rel_chain = RagasEvaluatorChain(metric=context_precision)
context_recall_chain = RagasEvaluatorChain(metric=context_recall)
```

**Comment by jjmachan** [comment]
hey @nils-hde could you try this notebook https://colab.research.google.com/drive/1C1Epju1lVkXTQi2jBq1njrOrmkfg0eQS?usp=sharing

I know it's too late - sorry about that
