### ISSUE TITLE
Expose LLM

### ISSUE THREAD

**Issue by HazK** [explodinggradients/ragas#46]
Hi,

Great piece of work here, really well done.

It would be fantastic if we could any supported LLM from langchain to do the evaluation. 

I have a number of use cases which require sovereignty, which means essentially either using on prem LLMs or Azure OpenAPI locked to a certain region.

Happy to help wherever I can!

**Comment by jjmachan** [comment]
hey, that for raising the issue and offering to help :)

We were a bit hesitant about adding langchain dependency because of how fast it keeps changing but if you could explain a bit more about your use cases that would help. 
Basically, what are you trying to improve by bringing in other LLMs? reduce cost? easily try out other LLMs for evaluation? If you could explain a bit about our thought process that would be awesome!

**Comment by HazK** [comment]
No problem!

Yes exactly - for a given use case in the enterprise there needs to be multiple choices factoring in performance, cost and the quality of results. In addition Azure OpenAPI offers privacy and compliance for the enterprise which is a cut above openAPI, hence it will become the "go to" for at least the next 6 months - at the moment a lot of organizations have closed off ChatGPT / OpenAPI together due to privacy and IP concerns.

**Comment by jjmachan** [comment]
alrighty, I will start on a draft to address this shortly. Thank you for the input @HazK 🙂

**Comment by HazK** [comment]
That sounds great thank you
________________________________

**Comment by jjmachan** [comment]
hey @HazK this is fixed. Thanks for bringing this up and do let us know when you try it
here is the example notebook: https://github.com/explodinggradients/ragas/blob/main/docs/guides/llms.ipynb
