### ISSUE TITLE
[R-275] Tokens Usage for evaluations and testset generations

### ISSUE THREAD

**Issue by aliai22** [explodinggradients/ragas#540]
I am using RAGAs evaluation metrics to evaluate my RAG pipeline. Is there any way I could know the openai tokens used per api call from RAGAs, lets say for any one metric, i.e., faithfulness. I want to estimate the cost of using RAGAs evaluators.

<sub>[R-275](https://linear.app/exploding-gradients/issue/R-275/tokens-usage-for-evaluations-and-testset-generations)</sub>

**Comment by jjmachan** [comment]
this is a valuable suggestion @aliai22 :)

we have thought about it and will be implementing it soon but it might take a couple of weeks to prioritize this. The reason is that I want to take some time to design how stats would be like

basically, we want to track things like
- tokens used
- cost
- performance metrics etc

in a unified way. I'll explore more and send an RFC your way asking for your feedback as soon as I have it ready. would that help?

**Comment by aliai22** [comment]
Yeah, that would be great. Looking forward to hear from you.

**Comment by Vishnu-add** [comment]
Did it get implemented?

**Comment by fhuthmacher** [comment]
I am also looking for this, any update?

**Comment by abetatos** [comment]
Pinging to see if this gets released at any point.

**Comment by nfsergiu** [comment]
Any updates on this @jjmachan ?

**Comment by whitney-meer** [comment]
I'm also interested in this!

**Comment by jjmachan** [comment]
hey folks, not yet but I will take this up this week and have something ready for your feedback shortly, my sincere apologies for the delay!

**Comment by jjmachan** [comment]
fixed in #1129
